This is a testharness.js-based test.
FAIL Cache API matching includes credentials promise_test: Unhandled rejection with value: object "SecurityError: Failed to execute 'delete' on 'CacheStorage': Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."
Harness: the test ran to completion.

